remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Preconditioning Optimal Transport
description: Exploring preconditioning techniques that accelerate the color transfer and video blending process
github:
    repository_nwo: https://github.com/owen-m1ller/ot-preconditioning
github_users:
    - csz23
    - galnnt
    - JennyChengxiXu
    - owen-m1ller
